declare class s1 implements AttributeModifier<StackAttribute> {
    applyNormalAttribute(instance: StackAttribute): void;
}
declare const o: s1;
declare class t1 implements AttributeModifier<ColumnAttribute> {
    applyNormalAttribute(instance: ColumnAttribute): void;
}
declare const t: t1;
declare class u1 implements AttributeModifier<RowAttribute> {
    applyNormalAttribute(instance: RowAttribute): void;
}
declare const u: u1;
declare class v1 implements AttributeModifier<FlexAttribute> {
    applyNormalAttribute(instance: FlexAttribute): void;
}
declare const a1: v1;
declare class w1 implements AttributeModifier<ScrollAttribute> {
    applyNormalAttribute(instance: ScrollAttribute): void;
}
declare const d1: w1;
declare class z1 implements AttributeModifier<ListAttribute> {
    applyNormalAttribute(instance: ListAttribute): void;
}
declare const e1: z1;
declare class a2 implements AttributeModifier<ListItemAttribute> {
    applyNormalAttribute(instance: ListItemAttribute): void;
}
declare const f1: a2;
declare class b2 implements AttributeModifier<ImageAttribute> {
    applyNormalAttribute(instance: ImageAttribute): void;
}
declare const g1: b2;
declare class c2 implements AttributeModifier<TextAttribute> {
    applyNormalAttribute(instance: TextAttribute): void;
}
declare const h1: c2;
declare class d2 implements AttributeModifier<TextInputAttribute> {
    applyNormalAttribute(instance: TextInputAttribute): void;
}
declare const i1: d2;
declare class e2 implements AttributeModifier<ButtonAttribute> {
    applyNormalAttribute(instance: ButtonAttribute): void;
}
declare const j1: e2;
declare class f2 implements AttributeModifier<TabsAttribute> {
    applyNormalAttribute(instance: TabsAttribute): void;
}
declare const b1: f2;
declare class g2 implements AttributeModifier<TabContentAttribute> {
    applyNormalAttribute(instance: TabContentAttribute): void;
}
declare const c1: g2;
declare class h2 implements AttributeModifier<SpanAttribute> {
    applyNormalAttribute(instance: SpanAttribute): void;
}
declare const l1: h2;
declare class i2 implements AttributeModifier<SwiperAttribute> {
    applyNormalAttribute(instance: SwiperAttribute): void;
}
declare const m1: i2;
declare class j2 implements AttributeModifier<ToggleAttribute> {
    applyNormalAttribute(instance: ToggleAttribute): void;
}
declare const n1: j2;
declare class l2 implements AttributeModifier<GridAttribute> {
    applyNormalAttribute(instance: GridAttribute): void;
}
declare const o1: l2;
declare class m2 implements AttributeModifier<GridItemAttribute> {
    applyNormalAttribute(instance: GridItemAttribute): void;
}
declare const q1: m2;
export { o, t, u, a1, b1, c1, d1, e1, f1, g1, h1, i1, j1, l1, m1, n1, o1, q1 };
